# Generated by Django 3.1.3 on 2020-12-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('tweets', '0002_auto_20201207_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='photos',
            field=models.ManyToManyField(blank=True, to='photos.Photo'),
        ),
    ]
